[package]
name = "cartographers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.16.0"
serde_json = "1.0.73"
enum-map = "1.1.1"
structopt = "0.3.25"